whitelist_rules:
  - trailing_whitespace
  - trailing_semicolon
  - trailing_newline
  - colon
  - comma
  - control_statement
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - MyBus/Pods
  - MyBus/MyBusTests