# Sources
source 'https://github.com/CocoaPods/Specs.git'

# Target
platform :ios, '9.0'
use_frameworks!

#Pods
target 'MYBUS' do
    pod 'Alamofire', '~> 4.2'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'SwiftyJSON', '~> 3.1'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~> 3.8'
    pod 'Mapbox-iOS-SDK', '~> 3.3'
    pod 'RealmSwift', '~> 2.1'
    pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'
    pod 'PageMenu', :git => 'https://github.com/orazz/PageMenu.git'
    pod 'Flurry-iOS-SDK', '~> 7.9'
    pod 'DZNEmptyDataSet', '~> 1.8'
    pod 'BetterSegmentedControl', '~> 0.7'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end

target 'MyBusTests' do
    pod 'Alamofire', '~> 4.2'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'SwiftyJSON', '~> 3.1'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~> 3.8'
    pod 'Mapbox-iOS-SDK', '~> 3.3'
    pod 'RealmSwift', '~> 2.1'
    pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'
    pod 'PageMenu', :git => 'https://github.com/orazz/PageMenu.git'
    pod 'Flurry-iOS-SDK', '~> 7.9'
    pod 'DZNEmptyDataSet', '~> 1.8'
    pod 'BetterSegmentedControl', '~> 0.7'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
    end
  end
end