# Sources
source 'https://github.com/CocoaPods/Specs.git'

# Target
platform :ios, '9.0'
use_frameworks!

#Pods
target 'MYBUS' do
    pod 'Alamofire', '~> 4.2'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'SwiftyJSON', '~> 4'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~> 3.8'
    pod 'Mapbox-iOS-SDK', '~> 3.6.4' # Since 3.7.0 until 3.7.3 exists a bug that crash the app
    pod 'RealmSwift', '~> 3.0'
    pod 'MapboxDirections.swift', '~> 0.10'
    pod 'PageMenu'
    pod 'Flurry-iOS-SDK', '~> 8.3'
    pod 'DZNEmptyDataSet', '~> 1.8'
    pod 'BetterSegmentedControl', '~> 0.7'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end

target 'MyBusTests' do
    pod 'Alamofire', '~> 4.2'
    pod 'MBProgressHUD', '~> 1.0'
    pod 'SwiftyJSON', '~> 4'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~> 3.8'
    pod 'Mapbox-iOS-SDK', '~> 3.6.4'
    pod 'RealmSwift', '~> 3.0'
    pod 'MapboxDirections.swift', '~> 0.10'
    pod 'PageMenu'
    pod 'Flurry-iOS-SDK', '~> 8.3'
    pod 'DZNEmptyDataSet', '~> 1.8'
    pod 'BetterSegmentedControl', '~> 0.7'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end


